// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: assignment/assignment.proto

package assignment

import (
	transaction "github.com/paphuc/protocol-buffers/transaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertAssignmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationID string                       `protobuf:"bytes,1,opt,name=correlationID,proto3" json:"correlationID,omitempty"`
	ID            int32                        `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                       `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	BeginTxRes    *transaction.BeginTxResponse `protobuf:"bytes,4,opt,name=beginTxRes,proto3" json:"beginTxRes,omitempty"`
}

func (x *InsertAssignmentRequest) Reset() {
	*x = InsertAssignmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assignment_assignment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAssignmentRequest) ProtoMessage() {}

func (x *InsertAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAssignmentRequest.ProtoReflect.Descriptor instead.
func (*InsertAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *InsertAssignmentRequest) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *InsertAssignmentRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *InsertAssignmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InsertAssignmentRequest) GetBeginTxRes() *transaction.BeginTxResponse {
	if x != nil {
		return x.BeginTxRes
	}
	return nil
}

type InsertAssignmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowAffected int32 `protobuf:"varint,1,opt,name=rowAffected,proto3" json:"rowAffected,omitempty"`
}

func (x *InsertAssignmentResponse) Reset() {
	*x = InsertAssignmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assignment_assignment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAssignmentResponse) ProtoMessage() {}

func (x *InsertAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAssignmentResponse.ProtoReflect.Descriptor instead.
func (*InsertAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{1}
}

func (x *InsertAssignmentResponse) GetRowAffected() int32 {
	if x != nil {
		return x.RowAffected
	}
	return 0
}

var File_assignment_assignment_proto protoreflect.FileDescriptor

var file_assignment_assignment_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1d, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x17, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x3c, 0x0a, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x22, 0x3c,
	0x0a, 0x18, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x6f,
	0x77, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x72, 0x6f, 0x77, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x32, 0x6d, 0x0a, 0x0a,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x5f, 0x0a, 0x10, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x23,
	0x2e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x70, 0x68, 0x75, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2d, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x73, 0x2f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x3b, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_assignment_assignment_proto_rawDescOnce sync.Once
	file_assignment_assignment_proto_rawDescData = file_assignment_assignment_proto_rawDesc
)

func file_assignment_assignment_proto_rawDescGZIP() []byte {
	file_assignment_assignment_proto_rawDescOnce.Do(func() {
		file_assignment_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(file_assignment_assignment_proto_rawDescData)
	})
	return file_assignment_assignment_proto_rawDescData
}

var file_assignment_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_assignment_assignment_proto_goTypes = []interface{}{
	(*InsertAssignmentRequest)(nil),     // 0: assignment.InsertAssignmentRequest
	(*InsertAssignmentResponse)(nil),    // 1: assignment.InsertAssignmentResponse
	(*transaction.BeginTxResponse)(nil), // 2: transaction.BeginTxResponse
}
var file_assignment_assignment_proto_depIdxs = []int32{
	2, // 0: assignment.InsertAssignmentRequest.beginTxRes:type_name -> transaction.BeginTxResponse
	0, // 1: assignment.Assignment.InsertAssignment:input_type -> assignment.InsertAssignmentRequest
	1, // 2: assignment.Assignment.InsertAssignment:output_type -> assignment.InsertAssignmentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_assignment_assignment_proto_init() }
func file_assignment_assignment_proto_init() {
	if File_assignment_assignment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_assignment_assignment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertAssignmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assignment_assignment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertAssignmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_assignment_assignment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assignment_assignment_proto_goTypes,
		DependencyIndexes: file_assignment_assignment_proto_depIdxs,
		MessageInfos:      file_assignment_assignment_proto_msgTypes,
	}.Build()
	File_assignment_assignment_proto = out.File
	file_assignment_assignment_proto_rawDesc = nil
	file_assignment_assignment_proto_goTypes = nil
	file_assignment_assignment_proto_depIdxs = nil
}
